### ISSUE TITLE
Hyperdx Loading...

### ISSUE THREAD

**Issue by satya-soul** [hyperdxio/hyperdx#483]
docker run -p 8000:8000 -p 4318:4318 -p 4317:4317 -p 8080:8080 -p 8002:8002 hyperdx/hyperdx-local

When I deployed it through docker I am getting loading page.
<img width="1455" alt="Screenshot 2024-07-29 at 3 58 28 PM" src="https://github.com/user-attachments/assets/0455fc94-866a-4f29-948f-1d1db8edb4cb">

**Comment by Buringcarbon** [comment]
I have the same problem

**Comment by MikeShi42** [comment]
Hi @satya-soul and @Buringcarbon are you guys both using non-localhost domains to access the page? Can you check if accessing on `localhost:8080` works?

It's most likely you'll need to edit the environment variables and rebuild the frontend app with the instructions here for custom domains: https://github.com/hyperdxio/hyperdx#:~:text=Changing%20Hostname%20and%20Port

**Comment by satya-soul** [comment]
Hey @MikeShi42 Thanks for the response, it did work on ec2 sever but still facing issue with getting logs from kubernetes. Do you know how to host it on Kubernetes? I have gone through a helm chart by one of open source contributor but still facing issue.

**Comment by MikeShi42** [comment]
@satya-soul the most important part is you'll need to have an image with the new domain baked in so that the frontend knows where to talk to the backend. I don't believe the helm chart takes care of that step today

**Comment by jokester** [comment]
Hosting the web UI at non-localhost origin requires some extra configuration

I can use this configuration at LAN host 192.168.2.120 , with no problem submitting and reading the traces

```
services:
  hyperdx:
    image: hyperdx/hyperdx-local:1.10.0
    environment:
      - FRONTEND_URL=http://192.168.2.120:8081
      - SERVER_URL=http://192.168.2.120:8000
    ports:
      - 8081:8080 # UI
      - 8000:8000 # API
      - 4318:4318 # http collector
      - 4317:4317 # gRPC collector
      - 8002:8002
```

```
$ OTEL_EXPORTER_OTLP_ENDPOINT=http://192.168.2.120:4318 node my-server.js
```
