### ISSUE TITLE
[helm chart] still redirect to localhost:3000

### ISSUE THREAD

**Issue by jovezhong** [hyperdxio/hyperdx#906]
I followed the guide at https://clickhouse.com/docs/use-cases/observability/clickstack/deployment/helm to install it on Google GKE. The app server was assigned with an external IP and I can access it it via http://external_ip:3000. After creating the account, I was redirected to http://localhost:3000

Then I checked the doc again and use the portforward
```bash
kubectl port-forward \
  pod/$(kubectl get pod -l app.kubernetes.io/name=hdx-oss-v2 -o jsonpath='{.items[0].metadata.name}') \
  8080:3000
```
Same issue. I was redirected from 8080 to 3000.

Maybe the 3000 is hardcoded somewhere in the JS code.

So my workaround is to portforward the 3000 to 3000
```bash
kubectl port-forward \
  pod/$(kubectl get pod -l app.kubernetes.io/name=hdx-oss-v2 -o jsonpath='{.items[0].metadata.name}') \
  3000:3000
```

Better to have this fixed

**Comment by dhable** [comment]
The `appPort` value is [defined in the helm chart values](https://github.com/hyperdxio/helm-charts/blob/main/charts/hdx-oss-v2/values.yaml#L10) and defaults to port 3000. That value is used to [set the `APP_PORT` config map value](https://github.com/hyperdxio/helm-charts/blob/36c4f5fb305cc20a5b9eefcd17e91d67ef5ab6ad/charts/hdx-oss-v2/templates/configmaps/app-configmap.yaml#L8), which I believe is how the redirect is being constructed. 

If you change the config map value, does it redirect to 8080?

**Comment by dhable** [comment]
Digging further, it looks like the the `FRONTEND_URL` config map entry is what is used in the code to construct redirect urls (e.g. from auth, etc). 

The [helm chart uses the default values](https://github.com/hyperdxio/hyperdx/blob/f05e58a913edc886dfe6cd669379248ccf2502ba/packages/api/src/middleware/auth.ts#L31) unless you override them when running `helm install`. Editing the config map object should be enough to fix redirect.

**Comment by jovezhong** [comment]
Thanks for looking into this. Last night I had to configure https, since I kept getting crypto JS error, because it was over http.

In GKE, I need to create a global external IP, a managed SSL cert, then create an ingress, something like this. 
```yaml
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: hyperdx.me.com
  namespace: default
spec:
  domains:
    - hyperdx.me.com

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hyperdx-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "hyperdx"
    networking.gke.io/managed-certificates: "hyperdx.me.com"
spec:
  rules:
    - host: hyperdx.me.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hyperdx-hdx-oss-v2-app
                port:
                  number: 3000


```

I will close this ticket, although I haven't tried configmap yet.
